Fix a couple of HTTP update issues
jakartaee/servlet pull request #501
Opened 2023-02-02 13:01 UTC by markt-asf

2023-02-02 22:32 UTC, stuartwdouglas requested changes

2023-02-02 22:32 UTC, stuartwdouglas commented on spec/src/main/asciidoc/servlet-spec-body.adoc
> +section 12.5.4 of RFC 9110 (HTTP SEmantics) for more information about how the
typo: SEmantics

2023-02-03 10:15 UTC, markt-asf commented on spec/src/main/asciidoc/servlet-spec-body.adoc
> +section 12.5.4 of RFC 9110 (HTTP SEmantics) for more information about how the
Fixed. Tx.

2023-02-03 10:15 UTC, stuartwdouglas approved these changes

2023-02-13 17:11 UTC, merged