Revert "Fix #525 FlushBufferTest"
jakartaee/servlet pull request #756
Opened 2024-11-08 18:27 UTC by pmd1nh

Reverts jakartaee/servlet#680

Hi,

The change in PR 680 has completely removed the old test, which has been around in many releases, and replaced with two new tests.  If the community thinks that the previous/old test is invalid, it should be excluded in the Servlet TCK 6.1.1.  Any new or replacement tests need to be added to the next servlet release.

PR 680 doesn’t follow the service release policy and needs to be reverted.

2024-11-08 18:27 UTC, pmd1nh commented
@markt-asf @gregw @olamy

2024-11-08 18:29 UTC, pmd1nh commented
@pnicolucci

2024-11-08 18:46 UTC, pnicolucci commented
Link to the TCK process: https://jakarta.ee/committees/specification/tckprocess/

I agree with @pmd1nh  here that these changes should be reverted in the 6.1.1 Servlet TCK service release. The following challenge needs to be revisited:  https://github.com/jakartaee/servlet/issues/525.

2024-11-08 19:38 UTC, markt-asf commented
#680 is fine - it updated master. The issue is the cherry-picking of it into the 6.1.x branch in 1b90c29

2024-11-08 19:39 UTC, markt-asf commented
This PR needs to be against 6.1.x, not master.

2024-11-08 19:41 UTC, markt-asf requested changes
This PR needs to be against 6.1.x rather than master.

It should also add the `@Ignore` annotation to the challenged test.

2024-11-08 20:52 UTC, pmd1nh commented
corrected branch to 6.1.X
added `@Ignore` to the `flushBufferTest()`

2024-11-08 21:34 UTC, markt-asf requested changes
Note sure what you have done but there are way too many changes included.

2024-11-09 03:41 UTC, pmd1nh commented
They show up after changing to the 6.1.X.

2024-11-11 00:45 UTC, pmd1nh commented
Reference #757

2024-11-11 00:45 UTC, closed without merging