Revert PR 680 and also Ignore the challenged test
jakartaee/servlet pull request #757
Opened 2024-11-11 00:41 UTC by pmd1nh

2024-11-11 01:15 UTC, pmd1nh commented
`@Ignore` is not available.  I try `@Disabled` and the build works.

2024-11-14 15:31 UTC, pmd1nh commented
@markt-asf Can you please review?  Thanks!

2024-11-14 15:54 UTC, pnicolucci commented
Does this doc need to be updated @markt-asf ? https://github.com/jakartaee/servlet/blob/6.1.x/tck/tck-docs/TCK-Exclude-List.txt

2024-11-15 08:52 UTC, markt-asf requested changes
The code changes LGTM. The TCK-Exclude-List.txt file does need to be updated.

2024-11-15 16:03 UTC, pmd1nh commented
> The code changes LGTM. The TCK-Exclude-List.txt file does need to be updated.

Updated

2024-11-18 07:54 UTC, markt-asf approved these changes

2024-11-18 07:55 UTC, merged

2025-01-07 16:57 UTC, pmd1nh commented
https://github.com/jakartaee/servlet/issues/525